package ca.webcadastre.model.entity;

// default package
// Generated Aug 8, 2018 4:59:45 PM by Hibernate Tools 5.3.0.Beta2

/**
 * AreaId generated by hbm2java
 */
public class AreaId implements java.io.Serializable {

	private int idArea;
	private String area;

	public AreaId() {
	}

	public AreaId(int idArea, String area) {
		this.idArea = idArea;
		this.area = area;
	}

	public int getIdArea() {
		return this.idArea;
	}

	public void setIdArea(int idArea) {
		this.idArea = idArea;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AreaId))
			return false;
		AreaId castOther = (AreaId) other;

		return (this.getIdArea() == castOther.getIdArea())
				&& ((this.getArea() == castOther.getArea()) || (this.getArea() != null && castOther.getArea() != null
						&& this.getArea().equals(castOther.getArea())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdArea();
		result = 37 * result + (getArea() == null ? 0 : this.getArea().hashCode());
		return result;
	}

}
