package ca.webcadastre.model.entity;

// default package
// Generated Aug 8, 2018 4:59:45 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private AreaId id;

	public Area() {
	}

	public Area(AreaId id) {
		this.id = id;
	}

	public AreaId getId() {
		return this.id;
	}

	public void setId(AreaId id) {
		this.id = id;
	}

}
