package ca.webcadastre.model.entity;

// default package
// Generated Aug 8, 2018 4:59:45 PM by Hibernate Tools 5.3.0.Beta2

/**
 * TypePropertyId generated by hbm2java
 */
public class TypePropertyId implements java.io.Serializable {

	private int idType;
	private String type;

	public TypePropertyId() {
	}

	public TypePropertyId(int idType, String type) {
		this.idType = idType;
		this.type = type;
	}

	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TypePropertyId))
			return false;
		TypePropertyId castOther = (TypePropertyId) other;

		return (this.getIdType() == castOther.getIdType())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdType();
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		return result;
	}

}
