package ca.webcadastre.model.entity;

// default package
// Generated Aug 8, 2018 4:59:45 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * TypeProperty generated by hbm2java
 */
public class TypeProperty implements java.io.Serializable {

	private TypePropertyId id;
	private Set properties = new HashSet(0);

	public TypeProperty() {
	}

	public TypeProperty(TypePropertyId id) {
		this.id = id;
	}

	public TypeProperty(TypePropertyId id, Set properties) {
		this.id = id;
		this.properties = properties;
	}

	public TypePropertyId getId() {
		return this.id;
	}

	public void setId(TypePropertyId id) {
		this.id = id;
	}

	public Set getProperties() {
		return this.properties;
	}

	public void setProperties(Set properties) {
		this.properties = properties;
	}

}
