package ca.webcadastre.model.entity;

/**
 * TypeProperty generated by hbm2java
 */
public class TypeProperty implements java.io.Serializable {

	private int idType;
	private String type;

	public TypeProperty() {
	}

	public int getIdType() {
		return idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
